# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
n_height = np.array(height)
n_weight = np.array(weight)

results = n_weight / (n_height**2) * 730
print(results)


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [35]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def makeMatrix(low,high,rows,columns,datatype = float):
    if datatype is int:
            return np.random.randint(low, high, (rows, columns))
    return np.random.uniform(low, high, (rows, columns))

print(makeMatrix(0,5,4,4))
print(makeMatrix(0,10,3,3,int))

[[1.83242805 4.97255142 3.72945418 0.93490508]
 [1.22320689 1.68410929 1.52813722 2.2490474 ]
 [1.3103593  1.73682567 0.85872775 0.59474946]
 [4.92419725 4.49637575 3.35947237 4.49175535]]
[[1 4 4]
 [1 2 8]
 [3 9 8]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [38]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, d=','):
    # Define an empty list to store data
    data = []
    
    with open(filename, encoding= 'utf-8') as mData:
        # use the csv reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        # Loop over info and append to data list
        for row in info:
            data.append(row)
        return data
csv_data = open_csv('../files/redsox_2017_hitting.txt')
print(csv_data[1:5])

[['1', 'C', 'Christian Vazquez', '26', '99', '345', '324', '43', '94', '18', '2', '5', '32', '7', '2', '17', '64', '.290', '.330', '.404', '.735', '91', '131', '14', '3', '0', '1', '0'], ['2', '1B', 'Mitch Moreland', '31', '149', '576', '508', '73', '125', '34', '0', '22', '79', '0', '1', '57', '120', '.246', '.326', '.443', '.769', '99', '225', '14', '6', '0', '5', '6'], ['3', '2B', 'Dustin Pedroia', '33', '105', '463', '406', '46', '119', '19', '0', '7', '62', '4', '3', '49', '48', '.293', '.369', '.392', '.760', '100', '159', '11', '2', '2', '4', '4'], ['4', 'SS', 'Xander Bogaerts', '24', '148', '635', '571', '94', '156', '32', '6', '10', '62', '15', '1', '56', '116', '.273', '.343', '.403', '.746', '95', '230', '17', '6', '0', '2', '6']]


In [50]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""
import statistics
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1, usecols = np.arange(0,24),
                        invalid_raise = False, names = FIELDS, dtype = DATATYPES)
    return data
data1 = load_data('../files/redsox_2017_hitting.txt')
data2 = load_data('../files/redsox_2018_hitting.txt')
# print(data1)
# print(data2)

avg1 = statistics.mean(data1['SLG'])
avg2 = statistics.mean(data2['SLG'])
print(avg1 - avg2)

0.0058478117
